FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet restore Samples/SecretManager.Edge/*.csproj
RUN dotnet publish Samples/SecretManager.Edge/*.csproj -c Release -o out

FROM mcr.microsoft.com/dotnet/runtime:5.0
WORKDIR /app
COPY --from=build-env /app/out ./

USER root
RUN mkdir /usr/local/cache
RUN chmod 777 /usr/local/cache

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "SecretManager.Edge.dll"]