name: deploy secret-delivery-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    paths:
      - SecretDeliveryApp/*
    branches: [master]

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: vislepakdemoacr.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vislepakdemoacr.azurecr.io/secret-delivery-app:${{ github.sha }}
          file: ./SecretDeliveryApp/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        working-directory: deployment
        run: |
          chmod +x deployApp.sh
          ./deployApp.sh secret-delivery \
          vislepakdemoacr.azurecr.io \
          vislepakdemoacr.azurecr.io/secret-delivery-app:${{ github.sha }} \
          ${{ secrets.AZURE_TENANT_ID }} \
          ${{ secrets.APP_CLIENT_ID }} \
          ${{ secrets.APP_SECRET }} \
          ${{ secrets.WEB_HOOK_APIKEY }} \
          ${{ secrets.KEYVAULT_URL }} \
          ${{ secrets.K8S_ENV_ID }} \
          ${{ IOT_HUB_CONNECTION_STRING }}
        shell: bash
